<?php 
class CalendarSDayNameDaysLV extends CalendarSDayEmpty
{
    public function getHtml ()
    {
        $allNames = self::allNames ();
        
        $todayNames = $allNames[$this->_dateTime->format ("n")][$this->_dateTime->format ("j")];
        
        if (empty ($todayNames))
            return "";
        
        return "<div class=\"names\">". implode("<br />", $todayNames) ."</div>";
    }
    /**
     * all names
     * @return array
     */
    public static function allNames ()
    {
        return array 
        (
            1 => array 
            (
                1 => array ('Solvita', 'Laimnesis', 'Solvija'),
                2 => array ('Ivo', 'Indulis', 'Ivis', 'Iva'),
                3 => array ('Miervaldis', 'Ringolds', 'Miervalda'),
                4 => array ('Ilva', 'Spodra', 'Ilvita'),
                5 => array ('Zintis', 'Sīmanis'),
                6 => array ('Arnita', 'Spulga'),
                7 => array ('Zigmārs', 'Rota', 'Juliāns', 'Digmārs'),
                8 => array ('Gatis', 'Ivanda'),
                9 => array ('Kaspars', 'Aksels', 'Alta'),
                10 => array ('Tatjana', 'Dorisa'),
                11 => array ('Smaida', 'Franciska'),
                12 => array ('Reinis', 'Renāts', 'Reinholds', 'Reina'),
                13 => array ('Harijs', 'Āris', 'Aira', 'Ārijs'),
                14 => array ('Roberts', 'Raitis', 'Roberta', 'Raits'),
                15 => array ('Fēlikss', 'Felicita'),
                16 => array ('Lidija', 'Lida'),
                17 => array ('Tenis', 'Dravis'),
                18 => array ('Antons', 'Antonijs', 'Antis'),
                19 => array ('Alnis', 'Andulis'),
                20 => array ('Oļģerts', 'Aļģirds', 'Orests', 'Alģis'),
                21 => array ('Agnese', 'Agnija', 'Agne'),
                22 => array ('Austris', 'Vincents'),
                23 => array ('Grieta', 'Strauta'),
                24 => array ('Ksenija', 'Krišs', 'Eglons'),
                25 => array ('Zigurds', 'Sigurds', 'Sigvards'),
                26 => array ('Ansis', 'Agnis', 'Agneta'),
                27 => array ('Ilze', 'Ildze', 'Izolde'),
                28 => array ('Kārlis', 'Spodris'),
                29 => array ('Aivars', 'Valērijs'),
                30 => array ('Valentīna', 'Pārsla', 'Tīna'),
                31 => array ('Tekla', 'Violeta'),
            ),
            
            2 => array 
            (
                1 => array ('Indra', 'Brigita', 'Indars', 'Indris'),
                2 => array ('Sonora', 'Spīdola'),
                3 => array ('Ida', 'Aīda', 'Vida'),
                4 => array ('Veronika', 'Daila', 'Dominiks'),
                5 => array ('Agate', 'Selga', 'Silga', 'Sinilga'),
                6 => array ('Dace', 'Dārta', 'Dora'),
                7 => array ('Rihards', 'Ričards', 'Nelda'),
                8 => array ('Česlavs', 'Aldona'),
                9 => array ('Simona', 'Apolonija'),
                10 => array ('Paula', 'Paulīne'),
                11 => array ('Laima', 'Laimdota'),
                12 => array ('Līna', 'Karlīna'),
                13 => array ('Melita', 'Malda'),
                14 => array ('Valentīns'),
                15 => array ('Olafs', 'Aloizs', 'Alvils', 'Olavs'),
                16 => array ('Jūlija', 'Džuljeta'),
                17 => array ('Donats', 'Donāts', 'Konstance'),
                18 => array ('Kintija', 'Kora'),
                19 => array ('Zane', 'Zuzanna'),
                20 => array ('Vitauts', 'Smuidra', 'Smuidris'),
                21 => array ('Eleonora', 'Ariadne'),
                22 => array ('Ārija', 'Adrians', 'Adrija', 'Adriāna', 'Rigonda'),
                23 => array ('Haralds', 'Almants'),
                24 => array ('Diāna', 'Dina', 'Dins'),
                25 => array ('Alma', 'Annemarija'),
                26 => array ('Evelīna', 'Aurēlija', 'Mētra'),
                27 => array ('Līva', 'Līvija', 'Andra'),
                28 => array ('Skaidrīte', 'Skaidra', 'Justs'),
                29 => array (),
            ),
            3 => array 
            (
                1 => array ('Ivars', 'Ilgvars'),
                2 => array ('Laila', 'Luīze', 'Lavīze'),
                3 => array ('Tālis', 'Marts', 'Tālavs'),
                4 => array ('Alise', 'Enija', 'Auce'),
                5 => array ('Austra', 'Aurora'),
                6 => array ('Vents', 'Centis', 'Gotfrīds'),
                7 => array ('Ella', 'Elmīra'),
                8 => array ('Dagmāra', 'Margita', 'Marga'),
                9 => array ('Ēvalds'),
                10 => array ('Silvija', 'Liliāna', 'Laimrota'),
                11 => array ('Konstantīns', 'Agita'),
                12 => array ('Aija', 'Aivis', 'Aiva'),
                13 => array ('Ernests', 'Balvis'),
                14 => array ('Matilde', 'Ulrika'),
                15 => array ('Imalda', 'Amalda', 'Amilda'),
                16 => array ('Guntis', 'Guntars', 'Guntris'),
                17 => array ('Gerda', 'Ģertrūde', 'Gertrūde'),
                18 => array ('Ilona', 'Adelīna'),
                19 => array ('Jāzeps', 'Juzefa'),
                20 => array ('Made', 'Irbe'),
                21 => array ('Una', 'Benedikts', 'Unigunde', 'Dzelme'),
                22 => array ('Tamāra', 'Gabriela', 'Gabriels', 'Dziedra'),
                23 => array ('Žanna', 'Mirdza', 'Žanete'),
                24 => array ('Kazimirs', 'Izidors'),
                25 => array ('Mārīte', 'Māra', 'Marita'),
                26 => array ('Ženija', 'Eiženija'),
                27 => array ('Gustavs', 'Gusts', 'Tālrīts'),
                28 => array ('Gunta', 'Ginta', 'Gunda'),
                29 => array ('Agija', 'Aldonis'),
                30 => array ('Ilgmārs', 'Nanija', 'Igmārs'),
                31 => array ('Gvido', 'Atvars'),
            ),
            4 => array
            (
                1 => array ('Dagnis', 'Dagne'),
                2 => array ('Irmgarde', 'Imgarde'),
                3 => array ('Dairis', 'Daira'),
                4 => array ('Valda', 'Herta', 'Ārvalds', 'Ārvalda'),
                5 => array ('Vija', 'Aivija', 'Vidaga'),
                6 => array ('Zinta', 'Filips', 'Dzinta', 'Vīlips'),
                7 => array ('Zinaīda', 'Helmuts', 'Zina'),
                8 => array ('Edgars', 'Dana', 'Danute', 'Dans'),
                9 => array ('Alla', 'Valērija', 'Žubīte'),
                10 => array ('Anita', 'Anitra', 'Zīle'),
                11 => array ('Vilmārs', 'Hermanis'),
                12 => array ('Ainis', 'Jūlijs'),
                13 => array ('Nauris', 'Egils', 'Egīls'),
                14 => array ('Strauja', 'Gudrīte'),
                15 => array ('Aelita', 'Gastons'),
                16 => array ('Bernadeta', 'Mintauts', 'Alfs'),
                17 => array ('Rūdolfs', 'Rūdis', 'Viviāna'),
                18 => array ('Laura', 'Jadviga'),
                19 => array ('Vēsma', 'Fanija'),
                20 => array ('Ziedīte', 'Mirta'),
                21 => array ('Anastasija', 'Marģers'),
                22 => array ('Armands', 'Armanda'),
                23 => array ('Juris', 'Jurģis', 'Georgs'),
                24 => array ('Visvaldis', 'Nameda', 'Ritvaldis'),
                25 => array ('Līksma', 'Bārbala'),
                26 => array ('Alīna', 'Sandris', 'Rūsiņš'),
                27 => array ('Raimonda', 'Raina', 'Klementīne', 'Tāle'),
                28 => array ('Gundega', 'Terēze'),
                29 => array ('Raimonds', 'Vilnis', 'Laine'),
                30 => array ('Lilija', 'Liāna'),
            ),
            5 => array
            (
                1 => array ('Ziedonis'),
                2 => array ('Zigmunds', 'Zigismunds', 'Sigmunds'),
                3 => array ('Gints', 'Uvis'),
                4 => array ('Viola', 'Vizbulīte', 'Vijolīte'),
                5 => array ('Ģirts', 'Ģederts'),
                6 => array ('Didzis', 'Gaidis'),
                7 => array ('Henrijs', 'Jete', 'Henriete'),
                8 => array ('Staņislavs', 'Staņislava', 'Stefānija'),
                9 => array ('Ervīns', 'Einārs', 'Klāvs'),
                10 => array ('Maija', 'Paija'),
                11 => array ('Milda', 'Karmena', 'Manfreds'),
                12 => array ('Ināra', 'Ina', 'Valija', 'Inārs'),
                13 => array ('Irina', 'Irēna', 'Ira', 'Iraīda'),
                14 => array ('Krišjānis', 'Aivita', 'Elvita', 'Elfa'),
                15 => array ('Sofija', 'Arita', 'Taiga', 'Airita'),
                16 => array ('Edvīns', 'Edijs'),
                17 => array ('Herberts', 'Dailis', 'Umberts'),
                18 => array ('Inese', 'Ēriks', 'Inesis'),
                19 => array ('Lita', 'Sibilla', 'Teika'),
                20 => array ('Salvis', 'Venta', 'Selva'),
                21 => array ('Ingmārs', 'Ernestīne', 'Akvelīna'),
                22 => array ('Emīlija', 'Visi kalendārā neiekļauti vārdi'),
                23 => array ('Leontīne', 'Lonija', 'Leokādija', 'Ligija'),
                24 => array ('Ilvija', 'Marlēna', 'Ziedone'),
                25 => array ('Junora', 'Anšlavs'),
                26 => array ('Eduards', 'Edvards', 'Varis'),
                27 => array ('Dzidra', 'Gunita', 'Loreta', 'Dzidris'),
                28 => array ('Vilis', 'Vilhelms'),
                29 => array ('Raivis', 'Raivo', 'Maksis'),
                30 => array ('Lolita', 'Vitolds', 'Letīcija'),
                31 => array ('Alīda', 'Jūsma'),
            ),
            6 => array
            (
                1 => array ('Biruta', 'Mairita', 'Bernedīne'),
                2 => array ('Emma', 'Lība'),
                3 => array ('Inta', 'Ineta', 'Intra'),
                4 => array ('Sintija', 'Sindija', 'Elfrīda'),
                5 => array ('Igors', 'Ingvars', 'Margots'),
                6 => array ('Ingrīda', 'Ardis'),
                7 => array ('Arnis', 'Gaida', 'Arno'),
                8 => array ('Frīda', 'Frīdis', 'Mundra'),
                9 => array ('Ligita', 'Gita', 'Felicijans'),
                10 => array ('Anatolijs', 'Anatols', 'Malva'),
                11 => array ('Ingus', 'Mairis', 'Vidvuds'),
                12 => array ('Nora', 'Ija', 'Lenora'),
                13 => array ('Ainārs', 'Zigfrīds', 'Uva'),
                14 => array ('Saiva', 'Tija', 'Santis', 'Sentis', 'Saivis'),
                15 => array ('Vilija', 'Vits', 'Baņuta', 'Žermēna'),
                16 => array ('Justīne', 'Juta'),
                17 => array ('Artūrs', 'Artis'),
                18 => array ('Alberts', 'Madis'),
                19 => array ('Viktors', 'Nils'),
                20 => array ('Rasma', 'Maira', 'Rasa'),
                21 => array ('Emīls', 'Egita', 'Monvīds'),
                22 => array ('Ludmila', 'Laimdots', 'Laimiņš'),
                23 => array ('Līga'),
                24 => array ('Jānis'),
                25 => array ('Maiga', 'Milija', 'Maigone'),
                26 => array ('Ausma', 'Inguna', 'Inguns', 'Ausmis'),
                27 => array ('Malvīne', 'Malvis'),
                28 => array ('Viesturs', 'Kitija', 'Viestards'),
                29 => array ('Pēteris', 'Pauls', 'Paulis', 'Pāvils'),
                30 => array ('Mareks', 'Tālivaldis'),
            ),
            7 => array 
            (
                1 => array ('Imants', 'Intars', 'Ingars', 'Rimants'),
                2 => array ('Lauma', 'Ilvars', 'Halina'),
                3 => array ('Benita', 'Everita', 'Verita'),
                4 => array ('Uldis', 'Sandis', 'Sandijs', 'Ulvis'),
                5 => array ('Edīte', 'Andžejs', 'Esmeralda', 'Andžs'),
                6 => array ('Arkādijs', 'Anrijs'),
                7 => array ('Maruta', 'Alda'),
                8 => array ('Antra', 'Adele', 'Ada'),
                9 => array ('Zaiga', 'Asne', 'Asna'),
                10 => array ('Lija', 'Olivers', 'Olīvija'),
                11 => array ('Leonora', 'Svens'),
                12 => array ('Ints', 'Indriķis', 'Namejs'),
                13 => array ('Margarita', 'Margrieta'),
                14 => array ('Oskars', 'Ritvars', 'Anvars'),
                15 => array ('Egons', 'Egija', 'Henrihs', 'Henriks', '...'),
                16 => array ('Estere', 'Hermīne'),
                17 => array ('Aleksejs', 'Aleksis'),
                18 => array ('Rozālija', 'Roze'),
                19 => array ('Jautrīte', 'Digna', 'Kamila'),
                20 => array ('Ramona', 'Ritma'),
                21 => array ('Melisa', 'Meldra', 'Meldris'),
                22 => array ('Marija', 'Marina', 'Marika', 'Marī'),
                23 => array ('Magdalēna', 'Mērija', 'Magda', 'Magone'),
                24 => array ('Kristīne', 'Kristiāna', 'Krista', 'Kristiāns'),
                25 => array ('Jēkabs', 'Žaklīna'),
                26 => array ('Anna', 'Annija', 'Ance'),
                27 => array ('Marta', 'Dita'),
                28 => array ('Cilda', 'Cecīlija'),
                29 => array ('Edmunds', 'Edžus', 'Vidmants'),
                30 => array ('Renārs', 'Valters', 'Regnārs'),
                31 => array ('Ruta', 'Rūta', 'Sigita', 'Angelika'),
            ),
            8 => array 
            (
                1 => array ('Albīna', 'Albīns'),
                2 => array ('Normunds', 'Stefans'),
                3 => array ('Augusts'),
                4 => array ('Romāns', 'Romualds', 'Romualda'),
                5 => array ('Osvalds', 'Arvils'),
                6 => array ('Askolds', 'Aisma'),
                7 => array ('Alfrēds', 'Madars', 'Fredis'),
                8 => array ('Vladislavs', 'Mudīte', 'Vladislava'),
                9 => array ('Madara', 'Genoveva'),
                10 => array ('Inuta', 'Audris', 'Brencis'),
                11 => array ('Olga', 'Zita', 'Liega', 'Zigita'),
                12 => array ('Vizma', 'Klāra'),
                13 => array ('Elvīra', 'Velga', 'Rēzija'),
                14 => array ('Zelma', 'Virma', 'Zemgus'),
                15 => array ('Zenta', 'Zelda', 'Dzelde'),
                16 => array ('Astrīda', 'Astra'),
                17 => array ('Oļegs', 'Vineta'),
                18 => array ('Liene', 'Helēna', 'Elena', 'Liena', 'Ellena'),
                19 => array ('Melānija', 'Imanta'),
                20 => array ('Boriss', 'Bernhards'),
                21 => array ('Linda', 'Janīna'),
                22 => array ('Rudīte', 'Everts'),
                23 => array ('Vitālijs', 'Ralfs', 'Valgudis'),
                24 => array ('Boļeslavs', 'Bērtulis'),
                25 => array ('Patrīcija', 'Ivonna', 'Ludvigs', 'Ludis'),
                26 => array ('Natālija', 'Broņislava', 'Broņislavs', 'Tālija'),
                27 => array ('Žanis', 'Alens', 'Jorens'),
                28 => array ('Auguste', 'Guste'),
                29 => array ('Aiga', 'Armīns', 'Vismants'),
                30 => array ('Jolanta', 'Samanta', 'Alvis'),
            ),
            9 => array 
            (
                1 => array ('Ilmārs', 'Iluta', 'Austrums'),
                2 => array ('Elīza', 'Lizete', 'Zete'),
                3 => array ('Berta', 'Bella'),
                4 => array ('Dzintra', 'Dzintars', 'Dzintara'),
                5 => array ('Klaudija', 'Vaida', 'Persijs'),
                6 => array ('Maigonis', 'Magnuss', 'Mariuss'),
                7 => array ('Regīna', 'Ermīns'),
                8 => array ('Ilga'),
                9 => array ('Bruno', 'Telma'),
                10 => array ('Jausma', 'Albertīne'),
                11 => array ('Signe', 'Signija'),
                12 => array ('Evita', 'Eva', 'Erna'),
                13 => array ('Izabella', 'Iza'),
                14 => array ('Santa', 'Sanita', 'Sanda', 'Sanija', 'Sandija'),
                15 => array ('Sandra', 'Gunvaldis', 'Sondra', 'Gunvaris'),
                16 => array ('Asja', 'Asnate', 'Dāgs', 'Dārgs'),
                17 => array ('Vera', 'Vaira', 'Vairis'),
                18 => array ('Elita', 'Liesma', 'Alita'),
                19 => array ('Verners', 'Muntis'),
                20 => array ('Marianna', 'Guntra', 'Ginters'),
                21 => array ('Modris', 'Matīss', 'Mariss'),
                22 => array ('Māris', 'Maigurs', 'Mārica'),
                23 => array ('Vanda', 'Veneranda', 'Venija'),
                24 => array ('Agris', 'Agrita'),
                25 => array ('Rodrigo', 'Rauls'),
                26 => array ('Gundars', 'Kurts', 'Knuts'),
                27 => array ('Ilgonis', 'Ādolfs'),
                28 => array ('Sergejs', 'Svetlana', 'Lana'),
                29 => array ('Mihails', 'Mikus', 'Miks', 'Miķelis'),
                30 => array ('Elma', 'Menarda', 'Elna'),
            ),
            10 => array 
            (
                1 => array ('Lāsma', 'Zanda', 'Zandis'),
                2 => array ('Ilma', 'Skaidris'),
                3 => array ('Elza', 'Ilizana'),
                4 => array ('Francis', 'Modra'),
                5 => array ('Amēlija', 'Amālija'),
                6 => array ('Monika', 'Zilgma', 'Zilga'),
                7 => array ('Daumants', 'Druvvaldis'),
                8 => array ('Aina', 'Anete', 'Dženeta'),
                9 => array ('Elga', 'Helga', 'Elgars'),
                10 => array ('Arvīds', 'Arvis', 'Druvis'),
                11 => array ('Monta', 'Silva', 'Tince'),
                12 => array ('Kira', 'Valfrīds'),
                13 => array ('Irma', 'Mirga'),
                14 => array ('Vilhelmīne', 'Minna'),
                15 => array ('Helvijs', 'Hedviga', 'Eda'),
                16 => array ('Daiga', 'Dinija'),
                17 => array ('Karīna', 'Gaitis', 'Gaits'),
                18 => array ('Rolands', 'Ronalds', 'Erlends', 'Rolanda'),
                19 => array ('Elīna', 'Drosma', 'Drosmis'),
                20 => array ('Leonīds', 'Leonīda'),
                21 => array ('Urzula', 'Severīns'),
                22 => array ('Īrisa', 'Airisa', 'Irīda'),
                23 => array ('Dainis', 'Daina', 'Dainida'),
                24 => array ('Renāte', 'Modrīte', 'Mudrīte'),
                25 => array ('Beāte', 'Beatrise'),
                26 => array ('Amanda', 'Kaiva', 'Amanta'),
                27 => array ('Lilita', 'Irita', 'Ita'),
                28 => array ('Ņina', 'Antoņina', 'Oksana', 'Ninona'),
                29 => array ('Laimonis', 'Elvis', 'Elvijs', 'Elva', 'Laimis'),
                30 => array ('Nadīna', 'Ulla', 'Adīna'),
                31 => array ('Rinalds', 'Valts', 'Rinalda'),
            ),
            11 => array
            (
                1 => array ('Ikars'),
                2 => array ('Vivita', 'Viva', 'Dzīle'),
                3 => array ('Ērika', 'Dagnija'),
                4 => array ('Atis', 'Oto', 'Otomārs'),
                5 => array ('Šarlote', 'Lote'),
                6 => array ('Leons', 'Linards', 'Leonards', 'Leonarda', 'Leo'),
                7 => array ('Lotārs', 'Helma'),
                8 => array ('Aleksandra', 'Agra'),
                9 => array ('Teodors'),
                10 => array ('Mārtiņš', 'Mārcis', 'Markuss'),
                11 => array ('Ojārs', 'Nellija', 'Rainers'),
                12 => array ('Kaija', 'Kornēlija'),
                13 => array ('Jevgēņijs', 'Eižens', 'Jevgēņija'),
                14 => array ('Fricis', 'Vikentijs', 'Vincents'),
                15 => array ('Undīne', 'Leopolds', 'Unda'),
                16 => array ('Glorija', 'Banga'),
                17 => array ('Uģis', 'Hugo', 'Uga'),
                18 => array ('Aleksandrs', 'Doloresa'),
                19 => array ('Elizabete', 'Betija', 'Līze', 'Liza'),
                20 => array ('Anda', 'Andīna'),
                21 => array ('Andis', 'Zeltīte'),
                22 => array ('Aldis', 'Alfons', 'Aldris'),
                23 => array ('Zigrīda', 'Zigfrīda', 'Zigrīds'),
                24 => array ('Velta', 'Velda'),
                25 => array ('Katrīna', 'Kate', 'Katrīne', 'Kadrija', 'Trīne'),
                26 => array ('Sebastians', 'Konrāds'),
                27 => array ('Lauris', 'Norberts'),
                28 => array ('Rita', 'Vita', 'Olita'),
                29 => array ('Ignats', 'Virgīnija'),
                30 => array ('Andrejs', 'Andris', 'Andrievs'),
            ),
            12 => array
            (
                1 => array ('Arnolds', 'Emanuels'),
                2 => array ('Sniedze', 'Meta'),
                3 => array ('Evija', 'Raita', 'Jogita'),
                4 => array ('Baiba', 'Barbara', 'Barba'),
                5 => array ('Sabīne', 'Sarma', 'Klaudijs'),
                6 => array ('Nikolajs', 'Niks', 'Niklāvs'),
                7 => array ('Antonija', 'Anta', 'Dzirkstīte'),
                8 => array ('Vladimirs', 'Gunārs', 'Gunis'),
                9 => array ('Sarmīte', 'Tabita'),
                10 => array ('Guna', 'Judīte'),
                11 => array ('Valdis', 'Voldemārs', 'Valdemārs'),
                12 => array ('Iveta', 'Otīlija'),
                13 => array ('Lūcija', 'Veldze'),
                14 => array ('Auseklis', 'Gaisma'),
                15 => array ('Jana', 'Hanna', 'Johanna'),
                16 => array ('Alvīne'),
                17 => array ('Hilda', 'Teiksma'),
                18 => array ('Kristaps', 'Kristers', 'Krists', 'Kristofers', 'Klinta'),
                19 => array ('Lelde', 'Sarmis'),
                20 => array ('Arta', 'Minjona'),
                21 => array ('Toms', 'Tomass', 'Saulcerīte'),
                22 => array ('Saulvedis'),
                23 => array ('Viktorija', 'Balva'),
                24 => array ('Ieva', 'Ādams'),
                25 => array ('Larisa', 'Stella'),
                26 => array ('Megija', 'Dainuvīte', 'Gija'),
                27 => array ('Inita', 'Elmārs', 'Helmars'),
                28 => array ('Inga', 'Ivita', 'Ingeborga', 'Irvita'),
                29 => array ('Solveiga', 'Ilgona'),
                30 => array ('Daniels', 'Dāvis', 'Daniela', 'Dāvids', 'Dāniels'),
                31 => array ('Kalvis', 'Silvestrs', 'Silvis'),
            )
        );

    }
}